sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ethancollins/multi-test -f ./client/Dockerfile.dev ./client

# If anything in the script section exits with a
# non-zero status code, the travis build will fail
script:
  - docker run -e CI=true ethancollins/multi-test npm test

# Build images after successful tests
after_success:
  - docker build -t ethancollins/multi-client ./client
  - docker build -t ethancollins/multi-nginx ./nginx
  - docker build -t ethancollins/multi-server ./server
  - docker build -t ethancollins/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push ethancollins/multi-client
  - docker push ethancollins/multi-nginx
  - docker push ethancollins/multi-server
  - docker push ethancollins/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-515281618347
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
