language: generic
sudo: required
services:
  - docker

before_install:
  - docker build - ethancollins/multi-test -f ./client/Dockerfile.dev ./client

# If anything in the script section exits with a
# non-zero status code, the travis build will fail
script:
  - docker run -e CI=true USERNAME/react-test npm test

# Build images after successful tests
after_success:
  - docker build -t ethancollins/multi-client ./client
  - docker build -t ethancollins/multi-nginx ./nginx
  - docker build -t ethancollins/multi-server ./server
  - docker build -t ethancollins/multi-worker ./worker
  # Log into the docker CLI
  - ECHO "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push ethancollins/multi-client
  - docker push ethancollins/multi-nginx
  - docker push ethancollins/multi-server
  - docker push ethancollins/multi-worker
